// Code generated by go generate; DO NOT EDIT.
// This file was generated at:
// 2021-03-19 16:10:28.575051592 &#43;0100 CET m=&#43;0.000851492
package horror

import "net/http"

// BadRequest return Error with given body and 400 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func BadRequest(body []byte) Error {
	return Status(http.StatusBadRequest, body)
}
// Unauthorized return Error with given body and 401 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func Unauthorized(body []byte) Error {
	return Status(http.StatusUnauthorized, body)
}
// PaymentRequired return Error with given body and 402 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func PaymentRequired(body []byte) Error {
	return Status(http.StatusPaymentRequired, body)
}
// Forbidden return Error with given body and 403 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func Forbidden(body []byte) Error {
	return Status(http.StatusForbidden, body)
}
// NotFound return Error with given body and 404 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func NotFound(body []byte) Error {
	return Status(http.StatusNotFound, body)
}
// MethodNotAllowed return Error with given body and 405 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func MethodNotAllowed(body []byte) Error {
	return Status(http.StatusMethodNotAllowed, body)
}
// NotAcceptable return Error with given body and 406 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func NotAcceptable(body []byte) Error {
	return Status(http.StatusNotAcceptable, body)
}
// ProxyAuthRequired return Error with given body and 407 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func ProxyAuthRequired(body []byte) Error {
	return Status(http.StatusProxyAuthRequired, body)
}
// RequestTimeout return Error with given body and 408 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func RequestTimeout(body []byte) Error {
	return Status(http.StatusRequestTimeout, body)
}
// Conflict return Error with given body and 409 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func Conflict(body []byte) Error {
	return Status(http.StatusConflict, body)
}
// Gone return Error with given body and 410 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func Gone(body []byte) Error {
	return Status(http.StatusGone, body)
}
// LengthRequired return Error with given body and 411 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func LengthRequired(body []byte) Error {
	return Status(http.StatusLengthRequired, body)
}
// PreconditionFailed return Error with given body and 412 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func PreconditionFailed(body []byte) Error {
	return Status(http.StatusPreconditionFailed, body)
}
// RequestEntityTooLarge return Error with given body and 413 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func RequestEntityTooLarge(body []byte) Error {
	return Status(http.StatusRequestEntityTooLarge, body)
}
// RequestURITooLong return Error with given body and 414 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func RequestURITooLong(body []byte) Error {
	return Status(http.StatusRequestURITooLong, body)
}
// UnsupportedMediaType return Error with given body and 415 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func UnsupportedMediaType(body []byte) Error {
	return Status(http.StatusUnsupportedMediaType, body)
}
// RequestedRangeNotSatisfiable return Error with given body and 416 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func RequestedRangeNotSatisfiable(body []byte) Error {
	return Status(http.StatusRequestedRangeNotSatisfiable, body)
}
// ExpectationFailed return Error with given body and 417 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func ExpectationFailed(body []byte) Error {
	return Status(http.StatusExpectationFailed, body)
}
// Teapot return Error with given body and 418 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func Teapot(body []byte) Error {
	return Status(http.StatusTeapot, body)
}
// MisdirectedRequest return Error with given body and 421 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func MisdirectedRequest(body []byte) Error {
	return Status(http.StatusMisdirectedRequest, body)
}
// UnprocessableEntity return Error with given body and 422 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func UnprocessableEntity(body []byte) Error {
	return Status(http.StatusUnprocessableEntity, body)
}
// Locked return Error with given body and 423 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func Locked(body []byte) Error {
	return Status(http.StatusLocked, body)
}
// FailedDependency return Error with given body and 424 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func FailedDependency(body []byte) Error {
	return Status(http.StatusFailedDependency, body)
}
// TooEarly return Error with given body and 425 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func TooEarly(body []byte) Error {
	return Status(http.StatusTooEarly, body)
}
// UpgradeRequired return Error with given body and 426 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func UpgradeRequired(body []byte) Error {
	return Status(http.StatusUpgradeRequired, body)
}
// PreconditionRequired return Error with given body and 428 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func PreconditionRequired(body []byte) Error {
	return Status(http.StatusPreconditionRequired, body)
}
// TooManyRequests return Error with given body and 429 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func TooManyRequests(body []byte) Error {
	return Status(http.StatusTooManyRequests, body)
}
// RequestHeaderFieldsTooLarge return Error with given body and 431 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func RequestHeaderFieldsTooLarge(body []byte) Error {
	return Status(http.StatusRequestHeaderFieldsTooLarge, body)
}
// UnavailableForLegalReasons return Error with given body and 451 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func UnavailableForLegalReasons(body []byte) Error {
	return Status(http.StatusUnavailableForLegalReasons, body)
}
// InternalServerError return Error with given body and 500 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func InternalServerError(body []byte) Error {
	return Status(http.StatusInternalServerError, body)
}
// NotImplemented return Error with given body and 501 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func NotImplemented(body []byte) Error {
	return Status(http.StatusNotImplemented, body)
}
// BadGateway return Error with given body and 502 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func BadGateway(body []byte) Error {
	return Status(http.StatusBadGateway, body)
}
// ServiceUnavailable return Error with given body and 503 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func ServiceUnavailable(body []byte) Error {
	return Status(http.StatusServiceUnavailable, body)
}
// GatewayTimeout return Error with given body and 504 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func GatewayTimeout(body []byte) Error {
	return Status(http.StatusGatewayTimeout, body)
}
// HTTPVersionNotSupported return Error with given body and 505 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func HTTPVersionNotSupported(body []byte) Error {
	return Status(http.StatusHTTPVersionNotSupported, body)
}
// VariantAlsoNegotiates return Error with given body and 506 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func VariantAlsoNegotiates(body []byte) Error {
	return Status(http.StatusVariantAlsoNegotiates, body)
}
// InsufficientStorage return Error with given body and 507 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func InsufficientStorage(body []byte) Error {
	return Status(http.StatusInsufficientStorage, body)
}
// LoopDetected return Error with given body and 508 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func LoopDetected(body []byte) Error {
	return Status(http.StatusLoopDetected, body)
}
// NotExtended return Error with given body and 510 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func NotExtended(body []byte) Error {
	return Status(http.StatusNotExtended, body)
}
// NetworkAuthenticationRequired return Error with given body and 511 http status code.
//
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
func NetworkAuthenticationRequired(body []byte) Error {
	return Status(http.StatusNetworkAuthenticationRequired, body)
}
